### ISSUE TITLE
Appearance related issues

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Dashboard#209]
- [x] Should zeroes be displayed https://github.com/IATI/IATI-Dashboard/issues/199
- [x] Should we have sticky headers https://github.com/IATI/IATI-Dashboard/issues/201
- [ ] Month column headers https://github.com/IATI/IATI-Dashboard/issues/210
- [ ] Highlight columns https://github.com/IATI/IATI-Dashboard/issues/214
